Fix j2 undefined handling
The patch fix handling attributes usage of a undefined variable like:

  {{ messaging.osconfig() }}
  {{ messaging.servers[5] }}

Without the patch the cases above will be failed with exception like this:
    AttributeError: 'str' object has no attribute '__call__'
because at any action on undefined variable the _fail_with_undefined_error
of SilentUndefined class returns empty string.

Change-Id: Ifa75ccef9bad7aeca13aeccb2470b38b03c1c139